//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Collections.Generic;
using System.Runtime.Serialization;

[DataContract(IsReference = true)]
public partial class Cart
{
    [DataMember]
    public int RecordId { get; set; }
    [DataMember]
    public string CartId { get; set; }
    [DataMember]
    public int ProduitId { get; set; }
    [DataMember]
    public Nullable<int> Count { get; set; }
    [DataMember]
    public Nullable<System.DateTime> DateCreated { get; set; }
    [DataMember]

    public virtual Produit Produit { get; set; }
}
