//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Collections.Generic;
using System.Runtime.Serialization;

[DataContract(IsReference = true)]
public partial class Genre
{
    public Genre()
    {
        this.Produit = new HashSet<Produit>();
    }
    [DataMember]
    public int GenreId { get; set; }
    [DataMember]
    public string Name { get; set; }
    [DataMember]
    public string Description { get; set; }
    [DataMember]

    public virtual ICollection<Produit> Produit { get; set; }
}
