//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Collections.Generic;
using System.Runtime.Serialization;
[DataContract(IsReference =true )]
public partial class OrderDetail
  
{
    [DataMember]
    public int OrderDetailID { get; set; }
    [DataMember]
    public int OrderId { get; set; }
    [DataMember]
    public int ProduitId { get; set; }
    [DataMember]
    public Nullable<int> Quantity { get; set; }
    [DataMember]
    public Nullable<decimal> UnitPrice { get; set; }
    [DataMember]

    public virtual Order Order { get; set; }
    [DataMember]
    public virtual Produit Produit { get; set; }
}
