//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Collections.Generic;
using System.Runtime.Serialization;

[DataContract(IsReference = true)]
public partial class Produit
{
    public Produit()
    {
        this.Cart = new HashSet<Cart>();
        this.OrderDetail = new HashSet<OrderDetail>();
    }
    [DataMember]
    public int ProduitId { get; set; }
    [DataMember]
    public Nullable<int> GenreId { get; set; }
    [DataMember]
    public Nullable<int> MarqueId { get; set; }
    [DataMember]
    public string Title { get; set; }
    [DataMember]
    public string Description { get; set; }
    [DataMember]
    public Nullable<decimal> Price { get; set; }
    [DataMember]

    public string Image { get; set; }
    [DataMember]
    public Nullable<int> Quantite { get; set; }
    [DataMember]

    public virtual ICollection<Cart> Cart { get; set; }
    [DataMember]
    public virtual Genre Genre { get; set; }
    [DataMember]
    public virtual Marque Marque { get; set; }
    [DataMember]
    public virtual ICollection<OrderDetail> OrderDetail { get; set; }
}
